trivia_messenger_homepage:
    path:  /messages
    defaults: { _controller: TriviaMessengerBundle:Messages:index }
trivia_messenger_login:
    path: /login
    defaults: { _controller: TriviaMessengerBunlde:User:login }
trivia_messenger_register:
    path: /register
    defaults: { _controller: TriviaMessengerBunlde:User:register }
trivia_messenger_profile:
    path: /profile
    defaults: { _controller: TriviaMessengerBunlde:User:register }
trivia_messenger_create:
    path: /messages/create
    defaults: { _controller: TriviaMessengerBundle:Messages:create }