parameters:
#    trivia_messenger.example.class: Trivia\MessengerBundle\Example

services:

   trivia.trivia_messenger.admin.kkaka:
      class: Trivia\MessengerBundle\Admin\UserAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: ulala, label: sosisochki}
      arguments: [null, Trivia\MessengerBundle\Entity\Users, TriviaMessengerBundle:UserAdmin]


